---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: monotf
  namespace: default
stringData:
  LOG_LEVEL: "debug"
  DB_DRIVER: ""
  DB_HOST: ""
  DB_PORT: ""
  DB_USER: ""
  DB_PASS: ""
  DB_NAME: ""
  DB_PATH: ""