---
apiVersion: v1
kind: Service
metadata:
  name: monotf
  namespace: default
  labels:
    app: monotf
spec:
  type: ClusterIP
  selector:
    app: monotf
  ports:
    - protocol: TCP
      port: 8080
      name: http
      targetPort: 8080